let products = [
    {
        id: 1,
        name: "Wireless Headphones",
        description: "High-quality wireless headphones with noise cancellation.",
        category: "Electronics",
        brand: "Sony",
        price: 59.99,
        article: 23001,
        discount: 70.99,
        deliveryTime: 5,
        rating: 4.5,
        image: [
            "../assets/images/products/1_1.png",
            "../assets/images/products/1_2.png",
            "../assets/images/products/1_3.png",
            "../assets/images/products/1_4.png",
        ],
    },
    {
        id: 2,
        name: "Smart Watch",
        category: "Electronics",
        brand: "Apple",
        description: "Waterproof smartwatch with fitness and heart rate tracking.",
        price: 89.99,
        article: 23002,
        discount: 110.99,
        deliveryTime: 2,
        rating: 4.0,
        image: [
            "../assets/images/products/2_1.png",
            "../assets/images/products/2_2.png",
            "../assets/images/products/2_3.png",
            "../assets/images/products/2_4.png",
        ],
    },
    {
        id: 3,
        name: "Bluetooth Speaker",
        category: "Electronics",
        brand: "JBL",
        description: "Portable mini speaker with deep bass and long battery life.",
        price: 34.99,
        article: 23003,
        deliveryTime: 4,
        discount: 48.99,
        rating: 4.0,
        image: [
            "../assets/images/products/3_1.png",
            "../assets/images/products/3_2.png",
            "../assets/images/products/3_3.png",
            "../assets/images/products/3_4.png",
        ],
    },
    {
        id: 4,
        name: "Running Shoes",
        category: "Fashion",
        brand: "Nike",
        description: "Lightweight and comfortable shoes perfect for everyday running.",
        discount: 85.99,
        price: 74.99,
        deliveryTime: 1,
        article: 24001,
        rating: 5.0,
        image: [
            "../assets/images/products/4_1.png",
            "../assets/images/products/4_2.png",
            "../assets/images/products/4_3.png",
            "../assets/images/products/4_4.png",
        ],
    },
    {
        id: 5,
        name: "Leather Wallet",
        category: "Accessories",
        brand: "Gucci",
        description: "Classic men's wallet made from genuine leather.",
        discount: 32.99,
        price: 24.99,
        deliveryTime: 6,
        article: 25001,
        rating: 4.0,
        image: [
            "../assets/images/products/5_1.png",
            "../assets/images/products/5_2.png",
            "../assets/images/products/5_3.png",
            "../assets/images/products/5_4.png",
        ],
    },
    {
        id: 6,
        name: "Sunglasses",
        description: "UV-protected sunglasses with stylish modern design.",
        discount: 25.99,
        category: "Accessories",
        brand: "Ray-Ban",
        price: 19.99,
        deliveryTime: 1,
        rating: 4.0,
        article: 25002,
        image: [
            "../assets/images/products/6_1.png",
            "../assets/images/products/6_2.png",
            "../assets/images/products/6_3.png",
            "../assets/images/products/6_4.png",
        ],
    },
    {
        id: 7,
        name: "Laptop Backpack",
        description: "Spacious waterproof backpack with a laptop compartment.",
        discount: 65.99,
        category: "Bags",
        brand: "Samsonite",
        price: 45.99,
        article: 26001,
        deliveryTime: 7,
        rating: 4.0,
        image: [
            "../assets/images/products/7_1.png",
            "../assets/images/products/7_2.png",
            "../assets/images/products/7_3.png",
            "../assets/images/products/7_4.png",
        ],
    },
    {
        id: 8,
        name: "Coffee Maker",
        category: "Home Appliances",
        brand: "Philips",
        description: "Automatic coffee machine for quick and fresh brewing.",
        discount: 79.99,
        price: 69.99,
        deliveryTime: 1,
        article: 27001,
        rating: 3.5,
        image: [
            "../assets/images/products/8_1.png",
            "../assets/images/products/8_2.png",
            "../assets/images/products/8_3.png",
            "../assets/images/products/8_4.png",
        ],
    },
    {
        id: 9,
        name: "T-shirt",
        category: "Fashion",
        brand: "H&M",
        description: "Soft cotton T-shirt available in multiple colors.",
        discount: 24.99,
        price: 14.99,
        deliveryTime: 5,
        article: 24002,
        rating: 2.0,
        image: [
            "../assets/images/products/9_1.png",
            "../assets/images/products/9_2.png",
            "../assets/images/products/9_3.png",
            "../assets/images/products/9_4.png",
        ],
    },
    {
        id: 10,
        name: "Gaming Mouse",
        category: "Electronics",
        brand: "Logitech",
        description: "RGB gaming mouse with high precision and ergonomic design.",
        discount: 49.99,
        price: 39.99,
        article: 23004,
        rating: 4.5,
        deliveryTime: 6,
        image: [
            "../assets/images/products/10_1.png",
            "../assets/images/products/10_2.png",
            "../assets/images/products/10_3.png",
            "../assets/images/products/10_4.png",
        ],
    },
    {
        id: 11,
        name: "SmartPhone",
        category: "Electronics",
        brand: "Samsung",
        description: "Latest smartphone with fast processor and high-quality camera.",
        discount: 599.99,
        price: 499.99,
        article: 23005,
        deliveryTime: 2,
        rating: 5.0,
        image: [
            "../assets/images/products/11_1.png",
            "../assets/images/products/11_2.png",
            "../assets/images/products/11_3.png",
            "../assets/images/products/11_4.png",
        ],
    },
    {
        id: 12,
        name: "Desk Lamp",
        category: "Home Decor",
        brand: "IKEA",
        description: "Adjustable LED desk lamp with touch control.",
        discount: 40.99,
        price: 29.99,
        article: 28001,
        deliveryTime: 1,
        rating: 4.5,
        image: [
            "../assets/images/products/12_1.png",
            "../assets/images/products/12_2.png",
            "../assets/images/products/12_3.png",
            "../assets/images/products/12_4.png",
        ],
    },
    {
        id: 13,
        name: "Wireless Keyboard",
        category: "Electronics",
        brand: "Dell",
        description: "Silent and slim wireless keyboard with rechargeable battery.",
        discount: 65.99,
        price: 54.99,
        article: 23006,
        rating: 2.0,
        deliveryTime: 4,
        image: [
            "../assets/images/products/13_1.png",
            "../assets/images/products/13_2.png",
            "../assets/images/products/13_3.png",
            "../assets/images/products/13_4.png",
        ],
    },
    {
        id: 14,
        name: "Office Chair",
        category: "Furniture",
        brand: "Herman Miller",
        description: "Ergonomic office chair with lumbar support and breathable mesh.",
        discount: 159.99,
        price: 129.99,
        article: 29001,
        deliveryTime: 3,
        rating: 5.0,
        image: [
            "../assets/images/products/14_1.png",
            "../assets/images/products/14_2.png",
            "../assets/images/products/14_3.png",
            "../assets/images/products/14_4.png",
        ],
    },
    {
        id: 15,
        name: "Wrist Bracelet",
        description: "Minimalist design bracelet made from stainless steel.",
        category: "Accessories",
        brand: "Fossil",
        article: 25003,
        discount: 22.10,
        price: 12.99,
        deliveryTime: 4,
        rating: 4.0,
        image: [
            "../assets/images/products/15_1.png",
            "../assets/images/products/15_2.png",
            "../assets/images/products/15_3.png",
            "../assets/images/products/15_4.png",
        ],
    },
    {
        id: 16,
        name: "Cooking Pan Set",
        category: "Home Appliances",
        brand: "Tefal",
        description: "Non-stick pan set suitable for all types of stoves.",
        article: 27002,
        discount: 99.99,
        price: 79.99,
        deliveryTime: 6,
        rating: 4.5,
        image: [
            "../assets/images/products/16_1.png",
            "../assets/images/products/16_2.png",
            "../assets/images/products/16_3.png",
            "../assets/images/products/16_4.png",
        ],
    },
    {
        id: 17,
        name: "Gaming Keyboard",
        category: "Electronics",
        brand: "Razer",
        description: "Mechanical keyboard with RGB lighting for pro gamers.",
        article: 23007,
        discount: 89.99,
        price: 69.99,
        deliveryTime: 3,
        rating: 5.0,
        image: [
            "../assets/images/products/17_1.png",
            "../assets/images/products/17_2.png",
            "../assets/images/products/17_3.png",
            "../assets/images/products/17_4.png",
        ],
    },
    {
        id: 18,
        name: "Wireless Charger",
        category: "Electronics",
        brand: "Anker",
        description: "Fast wireless charger compatible with all smartphones.",
        article: 23008,
        discount: 42.99,
        deliveryTime: 1,
        price: 22.99,
        rating: 4.5,
        image: [
            "../assets/images/products/18_1.png",
            "../assets/images/products/18_2.png",
            "../assets/images/products/18_3.png",
            "../assets/images/products/18_4.png",
        ],
    },
    {
        id: 19,
        name: "Casual Hoodie",
        description: "Comfortable hoodie made from soft fabric.",
        category: "Fashion",
        brand: "Zara",
        article: 24003,
        discount: 58.99,
        price: 34.99,
        deliveryTime: 6,
        rating: 4.0,
        image: [
            "../assets/images/products/19_1.png",
            "../assets/images/products/19_2.png",
            "../assets/images/products/19_3.png",
            "../assets/images/products/19_4.png",
        ],
    },
    {
        id: 20,
        name: "Jeans Pants",
        category: "Fashion",
        brand: "Levi’s",
        description: "Stylish blue denim jeans with slim fit.",
        article: 24004,
        discount: 55.99,
        deliveryTime: 2,
        price: 44.99,
        rating: 4.5,
        image: [
            "../assets/images/products/20_1.png",
            "../assets/images/products/20_2.png",
            "../assets/images/products/20_3.png",
            "../assets/images/products/20_4.png",
        ],
    },
    {
        id: 21,
        name: "Power Bank",
        category: "Electronics",
        brand: "Xiaomi",
        description: "10,000mAh portable power bank for fast charging.",
        discount: 49.99,
        article: 23009,
        price: 29.99,
        deliveryTime: 3,
        rating: 4.5,
        image: [
            "../assets/images/products/21_1.png",
            "../assets/images/products/21_2.png",
            "../assets/images/products/21_3.png",
            "../assets/images/products/21_4.png",
        ],
    },
    {
        id: 22,
        name: "Water Bottle",
        category: "Home & Kitchen",
        brand: "Contigo",
        description: "Reusable BPA-free water bottle with leak-proof lid.",
        article: 30001,
        discount: 24.99,
        price: 14.99,
        deliveryTime: 1,
        rating: 4.0,
        image: [
            "../assets/images/products/22_1.png",
            "../assets/images/products/22_2.png",
            "../assets/images/products/22_3.png",
            "../assets/images/products/22_4.png",
        ],
    },
    {
        id: 23,
        name: "Yoga Mat",
        category: "Sports",
        brand: "Adidas",
        article: 31001,
        description: "Non-slip yoga mat for comfortable home workouts.",
        discount: 45.99,
        price: 24.99,
        deliveryTime: 5,
        rating: 4.5,
        image: [
            "../assets/images/products/23_1.png",
            "../assets/images/products/23_2.png",
            "../assets/images/products/23_3.png",
            "../assets/images/products/23_4.png",
        ],
    },
    {
        id: 24,
        name: "Hair Dryer",
        description: "Compact and powerful hair dryer with 3 speed settings.",
        category: "Beauty",
        brand: "Remington",
        discount: 59.99,
        article: 32001,
        price: 39.99,
        deliveryTime: 1,
        rating: 4.5,
        image: [
            "../assets/images/products/24_1.png",
            "../assets/images/products/24_2.png",
            "../assets/images/products/24_3.png",
            "../assets/images/products/24_4.png",
        ],
    },
    {
        id: 25,
        name: "LED TV",
        category: "Electronics",
        brand: "LG",
        description: "40-inch Full HD LED TV with vibrant colors and smart features.",
        discount: 449.99,
        article: 23010,
        price: 349.99,
        rating: 5.0,
        deliveryTime: 5,
        image: [
            "../assets/images/products/25_1.png",
            "../assets/images/products/25_2.png",
            "../assets/images/products/25_3.png",
            "../assets/images/products/25_4.png",
        ],
    },
    {
        id: 26,
        name: "Sports Watch",
        description: "Durable sports watch with stopwatch and waterproof design.",
        category: "Fashion",
        brand: "Casio",
        discount: 79.99,
        article: 24005,
        deliveryTime: 7,
        price: 59.99,
        rating: 4.0,
        image: [
            "../assets/images/products/26_1.png",
            "../assets/images/products/26_2.png",
            "../assets/images/products/26_3.png",
            "../assets/images/products/26_4.png",
        ],
    },
    {
        id: 27,
        name: "Travel Suitcase",
        description: "Lightweight hard-shell suitcase with TSA lock.",
        category: "Bags",
        brand: "American Tourister",
        discount: 129.99,
        article: 26002,
        price: 89.99,
        deliveryTime: 1,
        rating: 5.0,
        image: [
            "../assets/images/products/27_1.png",
            "../assets/images/products/27_2.png",
            "../assets/images/products/27_3.png",
            "../assets/images/products/27_4.png",
        ],
    },
    {
        id: 28,
        name: "Perfume",
        category: "Beauty",
        brand: "Chanel",
        description: "Long-lasting perfume with a fresh and elegant scent.",
        article: 32002,
        discount: 79.99,
        price: 49.99,
        rating: 4.5,
        deliveryTime: 6,
        image: [
            "../assets/images/products/28_1.png",
            "../assets/images/products/28_2.png",
            "../assets/images/products/28_3.png",
            "../assets/images/products/28_4.png",
        ],
    },
    {
        id: 29,
        name: "Wireless Earbuds",
        category: "Electronics",
        brand: "Apple",
        description: "Compact earbuds with clear sound and noise cancellation.",
        discount: 99.99,
        article: 23011,
        price: 69.99,
        rating: 5.0,
        deliveryTime: 4,
        image: [
            "../assets/images/products/29_1.png",
            "../assets/images/products/29_2.png",
            "../assets/images/products/29_3.png",
            "../assets/images/products/29_4.png",
        ],
    },
    {
        id: 30,
        name: "Smart Tablet",
        category: "Electronics",
        brand: "Huawei",
        description: "High-resolution tablet perfect for work, study, and entertainment.",
        discount: 399.99,
        article: 23012,
        price: 299.99,
        deliveryTime: 3,
        rating: 4.5,
        image: [
            "../assets/images/products/30_1.png",
            "../assets/images/products/30_2.png",
            "../assets/images/products/30_3.png",
            "../assets/images/products/30_4.png",
        ],
    },
];
